# Generated by Django 5.0.4 on 2024-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('rank', models.CharField(max_length=50)),
                ('security_clearance', models.CharField(choices=[('LEVEL_1', 'Level 1'), ('LEVEL_2', 'Level 2'), ('LEVEL_3', 'Level 3')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.TextField()),
            ],
        ),
    ]
